server:
  port: 8888
spring:
  profiles.active: prod
  application.name: USER-SERVICE
  jpa.hibernate.ddl-auto: none
  datasource.initialization-mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/greatlearning?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: pluralsight

management:
  security:
    enabled: false