DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (username)
);

CREATE TABLE authorities (
  username VARCHAR(50) NOT NULL,
  authority VARCHAR(50) NOT NULL,
  FOREIGN KEY (username) REFERENCES users(username)
);

CREATE UNIQUE INDEX ix_auth_username on authorities (username,authority);

CREATE TABLE IF NOT EXISTS ITEM (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  NUMBER_OF_ITEMS_AVAILABLE INT,
  PRICE INT
);

CREATE TABLE IF NOT EXISTS AUDIT (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER VARCHAR(50) NOT NULL,
  ITEMS VARCHAR(100) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  TOTAL_PRICE INT,
  TIME DATETIME
);

DROP VIEW IF EXISTS USER1_ORDERS;
CREATE VIEW USER1_ORDERS AS
SELECT * FROM AUDIT WHERE USER = 'user1';

DROP VIEW IF EXISTS USER2_ORDERS;
CREATE VIEW USER2_ORDERS AS
SELECT * FROM AUDIT WHERE USER = 'user2';
