DELETE FROM authorities WHERE username = 'admin';
DELETE FROM users WHERE username = 'admin';
COMMIT;

DROP VIEW IF EXISTS ALL_SALES_IN_DIFFERENT_CITIES;
CREATE VIEW ALL_SALES_IN_DIFFERENT_CITIES AS
SELECT * FROM AUDIT;

DROP VIEW IF EXISTS MAX_SALES_IN_LAST_MONTH;
CREATE VIEW MAX_SALES_IN_LAST_MONTH AS
SELECT * FROM AUDIT WHERE
TIME > now() - INTERVAL 30 DAY AND TOTAL_PRICE = (SELECT MAX(TOTAL_PRICE) FROM AUDIT);

DROP VIEW IF EXISTS ALL_SALES_IN_LAST_YEAR;
CREATE VIEW ALL_SALES_IN_LAST_YEAR AS
SELECT * FROM AUDIT WHERE
TIME < now() - INTERVAL 365 DAY;